name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  all:
    name: All

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt -- --check

      - name: Lint
        run: cargo clippy
